language: java
sudo: false
dist: trusty
jdk:
  - openjdk8
before_install:
  - sudo apt-get install -y awscli
  - sudo apt-get update -yq
  - eval "$(gimme 1.8.3)"
script:
  - ./gradlew check
  - if [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then
      frameworks/cassandra/build.sh aws;
      frameworks/elastic/build.sh aws;
      frameworks/hdfs/build.sh aws;
      frameworks/kafka/build.sh aws;
      frameworks/zookeeper/build.sh aws;
      frameworks/couchdb/build.sh aws;
      frameworks/portworx/build.sh aws;
    fi
notifications:
  email:
    on_success: always
    on_failure: always

  
